config/routes.rb
Rails.application.routes.draw do
  resources :walls do
    resources :posts
  end
  
  resources :posts do
    member do
      put "like" => "posts#upvote"
      put "unlike" => "posts#downvote"
    end
  end
  
  get 'welcome/index'

  devise_for :users
  
  root to: "welcome#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wall.rb
class Wall < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    validates :access_id, presence: true, length: { minimum: 5 }
    has_many :posts
    has_one :user
    belongs_to :post, :optional => true
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  before_action :set_wall, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  def access
    @walls = Wall.find(params[:id])
    
  end
  
  # GET /walls
  # GET /walls.json
  def index
    @walls = Wall.all
  end

  # GET /walls/1
  # GET /walls/1.json
  def show
  end

  # GET /walls/new
  def new
    @wall = Wall.new
  end

  # GET /walls/1/edit
  def edit
  end

  # POST /walls
  # POST /walls.json
  def create
    @wall = Wall.new(wall_params)
    @wall.user_id = current_user.id
    respond_to do |format|
      if @wall.save
        format.html { redirect_to @wall, notice: 'Wall was successfully created.' }
        format.json { render :show, status: :created, location: @wall }
      else
        format.html { render :new }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walls/1
  # PATCH/PUT /walls/1.json
  def update
    respond_to do |format|
      if @wall.update(wall_params)
        format.html { redirect_to @wall, notice: 'Wall was successfully updated.' }
        format.json { render :show, status: :ok, location: @wall }
      else
        format.html { render :edit }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walls/1
  # DELETE /walls/1.json
  def destroy
    @wall.destroy
    respond_to do |format|
      format.html { redirect_to walls_url, notice: 'Wall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def require_login
      unless current_user
        redirect_to "/users/sign_in"
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wall
      @wall = Wall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wall_params
      params.require(:wall).permit(:title, :user_id, :access_id)
    end
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/walls/_form.html.erb
<%= form_with(model: wall, local: true) do |form| %>
  <% if wall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wall.errors.count, "error") %> prohibited this wall from being saved:</h2>

      <ul>
      <% wall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :wall_title %>
  </div>


  <div class="field">
    <%= form.label :access_id %>
    <%= form.text_field :access_id, id: :wall_access_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/walls/edit.html.erb
<body>
   <nav class="purple lighten lighten-1" role="navigation" style="height: 95px; position:fixed;top:0;left:0;width:100%;">
    <div class="nav-wrapper">
      <a href="/welcome/index" class="brand-logo"a>
          <img src="https://i.imgur.com/1oAIFYE.png" alt="log"
          title="splatlog"
          style="width: 178px; height: 158px;">
         
      <ul class="right hide-on-med-and-down">
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/walls/new">Create New Wall</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/edit">Profile</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/sign_in">Log In</a></li>
      </ul>
    </div>
  </nav>
    <div class="container" style="text-align: center; margin-top: -21px; height: 59px;"><br>
    </div>
    <div class="container" style="text-align: center;"><br>
    </div>
    <div class="container" style="text-align: center;"><br>
    </div>
    <div class="container">
      <div style="text-align: center;"><br>
      </div>
    </div>
       <div class="row">
    <div class="col s6 offset-s3">
      <div class="card purple lighten lighten-1">
        <div class="card-content white-text">
          <span class="card-title">Editing Wall</span>
         <%= render 'form', wall: @wall %>

<%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">Show</button>'.html_safe, @wall %>
<%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">Back</button>'.html_safe, walls_path %>

        </div>
        <div class="card-action">
          
        </div>
    
  
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
  </body>
  <footer class="purple lighten-2" style="position:fixed;bottom:0;left:0;width:100%;"> <br>
      <div class="footer-copyright" style="position:fixed;bottom:0;left:0;width:100%;">
        <div class="container"> Made by <span style="color: #fef5fd;">Splat</span>
        </div>
      </div>
    </footer>
</html>

app/views/walls/index.html.erb
<p id="notice"><%= notice %></p>

<body>
    <nav class="purple lighten lighten-1" role="navigation" style="height: 95px; position:fixed;top:0;left:0;width:100%;">
    <div class="nav-wrapper">
      <a href="/welcome/index" class="brand-logo"a>
          <img src="https://i.imgur.com/1oAIFYE.png" alt="log"
          title="splatlog"
          style="width: 178px; height: 158px;">
         
      <ul class="right hide-on-med-and-down">
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/walls/new">Create New Wall</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/edit">Profile</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/sign_in">Log In</a></li>
      </ul>
    </div>
  </nav>
<br><br><br><br><br><br>

 <div class="row">
    <div class="col s6 offset-s3">
      <div class="card purple lighten lighten-1">
        <div class="card-content white-text">
          <span class="card-title">Walls</span>
         <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Access</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @walls.each do |wall| %>
      <% if wall.user_id == current_user.id %>
      <tr>
        <td><%= wall.title %></td>
        <td><%= User.find(wall.user_id).username %></td>
        <td><%= wall.access_id %></td>
        <td><%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">Show</button>'.html_safe, wall %></td>
        <td><%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">Edit</button>'.html_safe, edit_wall_path(wall) %></td>
        <td><%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">Destroy</button>'.html_safe, wall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<td><%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">New Wall</button>'.html_safe, new_wall_path %></td>

        </div>
        <div class="card-action">
          
        </div>
      </div>
    </div>
  </div>




</body>

<footer class="purple lighten-2" style="position:fixed;bottom:0;left:0;width:100%;"> <br>
      <div class="footer-copyright">
        <div class="container"> Made by <span style="color: #fef5fd;">Splat</span>
        </div>
      </div>
    </footer>
    
<br>

app/views/walls/new.html.erb
<p id="notice"><%= notice %></p>

<body>
    <nav class="purple lighten lighten-1" role="navigation" style="height: 95px; position:fixed;top:0;left:0;width:100%;">
    <div class="nav-wrapper">
      <a href="/welcome/index" class="brand-logo"a>
          <img src="https://i.imgur.com/1oAIFYE.png" alt="log"
          title="splatlog"
          style="width: 178px; height: 158px;">
         
      <ul class="right hide-on-med-and-down">
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/walls/new">Create New Wall</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/edit">Profile</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/sign_in">Log In</a></li>
      </ul>
    </div>
  </nav>
    <br><br><br><br><br><br><br><br>
     <div class="row">
    <div class="col s6 offset-s3">
      <div class="card purple lighten lighten-1">
        <div class="card-content white-text">
          <span class="card-title">Create New Wall</span>
           <%= render 'form', wall: @wall %>

          <%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">Back</button>'.html_safe, walls_path %>
        </div>
        <div class="card-action">
          
        </div>
      </div>
    </div>
  </div>
    
    
    
   
  </body>
 <footer class="purple lighten-2" style="position:fixed;bottom:0;left:0;width:100%;"> <br>
      <div class="footer-copyright">
        <div class="container"> Made by <span style="color: #fef5fd;">Splat</span>
        </div>
      </div>
    </footer>

app/views/walls/show.html.erb
<nav class="purple lighten lighten-1" role="navigation" style="height: 95px; position:fixed;top:0;left:0;width:100%;">
    <div class="nav-wrapper">
      <a href="/welcome/index" class="brand-logo"a>
          <img src="https://i.imgur.com/1oAIFYE.png" alt="log"
          title="splatlog"
          style="width: 178px; height: 158px;">
         
      <ul class="right hide-on-med-and-down">
       <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/walls/new">Create New Wall</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/edit">Profile</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/sign_in">Log In</a></li>
      </ul>
    </div>
</nav>
<br><br><br><br><br><br><br><br><br>
<p id="notice"><%= notice %></p>
<center>
<h3>
  <%= @wall.title %>
</h3>

<p>
  <strong>Wall ID:</strong>
  <%= @wall.id %>
</p>

<p>
  <strong>Wall Owner:</strong>
  <%= User.find(@wall.user_id).username %>
</p>

<p>
  <strong>Access:</strong>
  <%= @wall.access_id %>
</p>
</center>
<% @wall.posts.each do |post| %>

  <div class="row">
    <div class="col s6 offset-s3">
      <div class="card purple lighten lighten-1">
        <div class="card-content white-text">
          <span class="card-title"></span>
         <%= post.body %>
        </div>
        <div class="card-action">
          <span class="amber-text"><%= User.find(post.user_id).username%></span>
          <%= link_to like_post_path(post), method: :put do %>
          Like
          <%= post.get_upvotes.size %>
          <% end %>
        
          <%= link_to unlike_post_path(post), method: :put do %>
          Unlike
          <%= post.get_downvotes.size %>
          
        <% end %>
        
        </div>
      </div>
    </div>
  </div>

  
<% end %>
  <div class="row">
    <div class="col s6 offset-s3">
      <div class="card purple lighten lighten-1">
        <div class="card-content white-text">
          <span class="card-title">Add a Splat</span>
           <%= form_for([@wall, @wall.posts.build]) do |f| %>
 
  <p>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
        </div>
        <div class="card-action">


<%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">Edit</button>'.html_safe, edit_wall_path(@wall) %>
<%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">Back</button>'.html_safe, walls_path %>


<footer class="purple lighten-2" style="position:fixed;bottom:0;left:0;width:100%;"> <br>
      <div class="footer-copyright" style="position:fixed;bottom:0;left:0;width:100%;">
        <div class="container"> Made by <span style="color: #fef5fd;">Splat</span>
        </div>
      </div>
</footer>