config/routes.rb
Rails.application.routes.draw do
  resources :walls do
    resources :posts
  end
  
  resources :posts do
    member do
      put "like" => "posts#upvote"
      put "unlike" => "posts#downvote"
    end
  end
  
  get 'welcome/index'

  devise_for :users
  
  root to: "welcome#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    acts_as_votable
    belongs_to :user
    belongs_to :wall, :optional => true
    has_one :wall
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    set_post
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.wall_id = Wall.find(params[:wall_id]).id
    
    @wall = Wall.find(params[:wall_id])
    respond_to do |format|
      if @post.save
        format.html { redirect_to @wall, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # upvote method
  def upvote
    @post = Post.find(params[:id])
    @post.upvote_from current_user
    redirect_back(fallback_location: posts_path)
  end
  
  # downvote method
  def downvote
    @post = Post.find(params[:id])
    @post.downvote_from current_user
    redirect_back(fallback_location: posts_path)
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :user_id, :wall_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @posts, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<body>
    <nav class="purple lighten lighten-1" role="navigation" style="height: 95px; position:fixed;top:0;left:0;width:100%;">
    <div class="nav-wrapper">
      <a href="/welcome/index" class="brand-logo"a>
          <img src="https://i.imgur.com/1oAIFYE.png" alt="log"
          title="splatlog"
          style="width: 178px; height: 158px;">
         
      <ul class="right hide-on-med-and-down">
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/walls/new">Create New Wall</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/edit">Profile</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/sign_in">Log In</a></li>
      </ul>
    </div>
  </nav>
        
    
    <div class="container" style="text-align: center; margin-top: -21px; height: 59px;"><br>
    </div>
    <div class="container" style="text-align: center;"><br>
    </div>
    <div class="container" style="text-align: center;"><br>
    </div>
    <div><br><br><br><br>
<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
  </body>
 <footer class="purple lighten-2" style="position:fixed;bottom:0;left:0;width:100%;"> <br>
      <div class="footer-copyright">
        <div class="container"> Made by <span style="color: #fef5fd;">Splat</span>
        </div>
      </div>
    </footer>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

  
<body>
    <nav class="purple lighten lighten-1" role="navigation" style="height: 95px; position:fixed;top:0;left:0;width:100%;">
    <div class="nav-wrapper">
      <a href="/welcome/index" class="brand-logo"a>
          <img src="https://i.imgur.com/1oAIFYE.png" alt="log"
          title="splatlog"
          style="width: 178px; height: 158px;">
         
      <ul class="right hide-on-med-and-down">
      <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/walls/new">Create New Wall</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/edit">Profile</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/sign_in">Log In</a></li>
      </ul>
    </div>
  </nav>
    <div class="container" style="text-align: center; margin-top: -21px; height: 59px;"><br>
    </div>
    <div class="container" style="text-align: center;"><br>
    </div>
    <div class="container" style="text-align: center;"><br>
    </div>
    <div class="container"><br>
    <table>
  <thead>
    <tr>
      <th>Create New Wall</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.body %></td>
        <td><%= User.find(post.user_id).email %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
  </body>
 <footer class="purple lighten-2" style="position:fixed;bottom:0;left:0;width:100%;"> <br>
      <div class="footer-copyright">
        <div class="container"> Made by <span style="color: #fef5fd;">Splat</span>
        </div>
      </div>
    </footer>

app/views/posts/new.html.erb
<body>
    <nav class="purple lighten lighten-1" role="navigation" style="height: 95px; position:fixed;top:0;left:0;width:100%;">
    <div class="nav-wrapper">
      <a href="/welcome/index" class="brand-logo"a>
          <img src="https://i.imgur.com/1oAIFYE.png" alt="log"
          title="splatlog"
          style="width: 178px; height: 158px;">
         
      <ul class="right hide-on-med-and-down">
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/walls/new">Create New Wall</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/edit">Profile</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/sign_in">Log In</a></li>
      </ul>
    </div>
  </nav>
        
    
    <div class="container" style="text-align: center; margin-top: -21px; height: 59px;"><br>
    </div>
    <div class="container" style="text-align: center;"><br>
    </div>
    <div class="container" style="text-align: center;"><br>
    </div>
    <div><br><br><br><br>
 <%= render 'form', post: @post %>

<%= link_to 'Back',  '/walls/:wall_id/posts' %>
</div>

    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
  </body>
 <footer class="purple lighten-2" style="position:fixed;bottom:0;left:0;width:100%;"> <br>
      <div class="footer-copyright">
        <div class="container"> Made by <span style="color: #fef5fd;">Splat</span>
        </div>
      </div>
    </footer>

app/views/posts/show.html.erb
<body>
    <nav class="purple lighten lighten-1" role="navigation" style="height: 95px; position:fixed;top:0;left:0;width:100%;">
    <div class="nav-wrapper">
      <a href="/welcome/index" class="brand-logo"a>
          <img src="https://i.imgur.com/1oAIFYE.png" alt="log"
          title="splatlog"
          style="width: 178px; height: 158px;">
         
      <ul class="right hide-on-med-and-down">
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/walls/new">Create New Wall</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/edit">Profile</a></li>
        <li><a class="waves-effect waves amber darken-3 btn-large" style="color: white !important;" href="/users/sign_in">Log In</a></li>
      </ul>
    </div>
  </nav>
        
    
    <div class="container" style="text-align: center; margin-top: -21px; height: 59px;"><br>
    </div>
    <div class="container" style="text-align: center;"><br>
    </div>
    <div class="container" style="text-align: center;"><br>
    </div>
    <div><br><br><br><br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
  <%= link_to like_post_path(post), method: :put do %>
    Like
    <%= post.get_upvotes.size %>
    format.js {render inline: "location.reload();" }
  <% end %>
  
  <%= link_to unlike_post_path(post), method: :put do %>
    Unlike
    <%= post.get_downvotes.size %>
    format.js {render inline: "location.reload();" }
  <% end %>
</p>

<%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">Edit</button>'.html_safe, edit_post_path(@post) %>
<%= link_to '<button type="button" class="waves-effect waves amber darken-3 btn" style="color: white !important;">Back</button>'.html_safe, posts_path %>

</div>

    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
    <div class="container"><br>
    </div>
  </body>
 <footer class="purple lighten-2" style="position:fixed;bottom:0;left:0;width:100%;"> <br>
      <div class="footer-copyright">
        <div class="container"> Made by <span style="color: #fef5fd;">Splat</span>
        </div>
      </div>
    </footer>